import type { Metadata } from "next";
import "./globals.css";
import Footer from '@/components/footer';



export const metadata: Metadata = {
  title: "XYRON-Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="main-layout">
      
          <div className="content">
            {children}  {}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}